DATABASE:
  URL: postgres://vjnkuqoaneeraa:9cada12771ceb7c0e67faec3158231ced3ddc1f7cbc67bebbffcc53b0f36ddbd@ec2-99-80-170-190.eu-west-1.compute.amazonaws.com:5432/d56v0oj3iaok4u
  SYNCHRONIZE: true
  TYPE: 'postgres'

TELEGRAF:
  BOT_TOKEN: '5399446078:AAGsFt2JyCSUakqxAcXq7sWk9C0Yqn0WPKw'
